print("Hello World.. !!")
print("Hello ICT Academy")
print("Hello ICT Academy")
print("Hello ICT Academy")
print("Hello ICT Academy")
print("Hello ICT Academy")
print("Hello ICT Academy")
print("Hello ICT Academy")